# This workflow is triggered every time a change is pushed to any branches
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On Code Change

# The workflow could also be triggered on PRs
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  # The branch containing a releasable codebase, which could be either a main branch or a maintenance branch
  PRIMARY_RELEASE_BRANCH: main

jobs:
  build:
    name: Build Module
    needs: update-signature
    runs-on: ubuntu-latest
    container:
      image: jahia/cimg-mvn-cache:ga_cimg_openjdk_8.0.312-node
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:          
      - uses: actions/checkout@v2  
      - uses: jahia/jahia-modules-action/build@v1
        with:
          module_id: www-project-csrfguard
          mvn_settings_filepath: .github/maven.settings.xml

  publish:
    name: Publish module
    needs: [integration-tests, sonar-analysis]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: jahia/cimg-mvn-cache:ga_cimg_openjdk_8.0.312-node
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: jahia/jahia-modules-action/publish@v1
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
